### ISSUE TITLE
PDOException since last upgrade (v1.0.14)

### ISSUE THREAD

**Issue by BastienLQ** [passbolt/passbolt#13]
Hi,

I just updated passbolt to the latest git commit, and now I can't login.

```
2016-07-25 14:09:31 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')   ORDER BY `created` DESC  LIMIT 1' at line 1
Request URL: /auth/login.json
Stack Trace:
#0 /usr/local/src/passbolt/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /usr/local/src/passbolt/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('SELECT `Authent...', Array)
#2 /usr/local/src/passbolt/lib/Cake/Model/Datasource/DboSource.php(664): DboSource->execute('SELECT `Authent...', Array, Array)
#3 /usr/local/src/passbolt/lib/Cake/Model/Datasource/DboSource.php(1113): DboSource->fetchAll('SELECT `Authent...', false)
#4 /usr/local/src/passbolt/lib/Cake/Model/Model.php(3031): DboSource->read(Object(AuthenticationToken), Array)
#5 /usr/local/src/passbolt/lib/Cake/Model/Model.php(3003): Model->_readDataSource('first', Array)
#6 /usr/local/src/passbolt/app/Model/AuthenticationToken.php(146): Model->find('first', Array)
#7 /usr/local/src/passbolt/app/Controller/Component/Auth/GpgAuthenticate.php(126): AuthenticationToken::isValid('536e6f18-412b-4...', '57385cb8-1dd8-4...')
#8 /usr/local/src/passbolt/lib/Cake/Controller/Component/AuthComponent.php(766): GpgAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#9 /usr/local/src/passbolt/lib/Cake/Controller/Component/AuthComponent.php(611): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#10 /usr/local/src/passbolt/app/Controller/AuthController.php(35): AuthComponent->login()
#11 [internal function]: AuthController->login()
#12 /usr/local/src/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AuthController), Array)
#13 /usr/local/src/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#14 /usr/local/src/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthController), Object(CakeRequest))
#15 /usr/local/src/passbolt/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
```

Debian GNU/Linux 8 (jessie)
PHP 5.6.23+dfsg-0+deb8u1
php5-gnupg 1.3.3-1+b1
php5-json 1.3.6-1
MariaDB 10.1.8+maria-1~jessie
Linux 3.16.0-4-amd64 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

Thanks.

**Comment by stripthis** [comment]
Hi Bastien,

There was a change in the default configuration (app.php.default) that broke backward compatibility for existing config files. We're working on a fix to avoid that type of issues in the future, but in the meantime you can check in your app.php see if 'tokenExpiracy' => 4320 is missing.

It should look like this:
```
	// Authentication & Authorisation
	'Auth' => [
		'className' => 'PassboltAuth',
		'HashType' => 'blowfish',
		**// The number of minutes the authentication token lives for.
		'tokenExpiracy' => 4320,**
```

Let me know if this is something else.
Cheers,

**Comment by BastienLQ** [comment]
Yes, it works if I add the `tokenExpiracy` value in `app.php`. Thanks.

**Comment by stripthis** [comment]
ref.     PASSBOLT-1621

I'm leaving this open @BastienLQ for other people to see until a fix is released. Cheers,

**Comment by stripthis** [comment]
Fixed by v.1.1.0
